<?php

namespace AppBundle;

class Languages {

    public static function fromKey($key) {
        return array_search($key, self::$array);
    }

    public static function getArray() {
        return self::$array;
    }

    public static $array = array(
//        'Abap' => 'abap',
//        'Abc' => 'abc',
        'ActionScript' => 'actionscript',
//        'Ada' => 'ada',
        'Apache Conf' => 'apache_conf',
//        'Applescript' => 'applescript',
//        'Asciidoc' => 'asciidoc',
        'Assembly X86' => 'assembly_x86',
        'AutoHotkey' => 'autohotkey',
        'Batch' => 'batch',
//        'Bro' => 'bro',
//        'C9Search' => 'c9search',
//        'Cirru' => 'cirru',
//        'Clojure' => 'clojure',
//        'Cobol' => 'cobol',
//        'Coffee' => 'coffee',
//        'Coldfusion' => 'coldfusion',
        'C#' => 'csharp',
        'CSS' => 'css',
//        'Curly' => 'curly',
        'C/C++' => 'c_cpp',
        'D' => 'd',
        'Dart' => 'dart',
        'Diff' => 'diff',
        'Django' => 'django',
        'Dockerfile' => 'dockerfile',
//        'Dot' => 'dot',
//        'Drools' => 'drools',
//        'Eiffel' => 'eiffel',
//        'Ejs' => 'ejs',
//        'Elixir' => 'elixir',
//        'Elm' => 'elm',
//        'Erlang' => 'erlang',
//        'Forth' => 'forth',
//        'Fortran' => 'fortran',
//        'Ftl' => 'ftl',
//        'Gcode' => 'gcode',
//        'Gherkin' => 'gherkin',
        'Gitignore' => 'gitignore',
//        'Glsl' => 'glsl',
//        'Gobstones' => 'gobstones',
//        'Golang' => 'golang',
//        'Graphqlschema' => 'graphqlschema',
        'Groovy' => 'groovy',
        'Haml' => 'haml',
//        'Handlebars' => 'handlebars',
        'Haskell' => 'haskell',
//        'Haskell Cabal' => 'haskell_cabal',
//        'Haxe' => 'haxe',
        'Hjson' => 'hjson',
        'HTML' => 'html',
        'HTML Elixir' => 'html_elixir',
        'HTML Ruby' => 'html_ruby',
        'Ini' => 'ini',
//        'Io' => 'io',
//        'Jack' => 'jack',
//        'Jade' => 'jade',
        'Java' => 'java',
        'Javascript' => 'javascript',
        'Json' => 'json',
//        'Jsoniq' => 'jsoniq',
        'Jsp' => 'jsp',
//        'Jsx' => 'jsx',
//        'Julia' => 'julia',
        'Kotlin' => 'kotlin',
        'LaTeX' => 'latex',
//        'Lean' => 'lean',
        'Less' => 'less',
//        'Liquid' => 'liquid',
//        'Lisp' => 'lisp',
//        'Livescript' => 'livescript',
//        'Live Script' => 'live_script',
//        'Logiql' => 'logiql',
//        'Lsl' => 'lsl',
        'Lua' => 'lua',
//        'Luapage' => 'luapage',
//        'Lucene' => 'lucene',
        'Makefile' => 'makefile',
        'Markdown' => 'markdown',
//        'Mask' => 'mask',
        'Matlab' => 'matlab',
//        'Maze' => 'maze',
//        'Mel' => 'mel',
//        'Mipsassembler' => 'mipsassembler',
//        'Mips Assembler' => 'mips_assembler',
//        'Mushcode' => 'mushcode',
        'MySQL' => 'mysql',
//        'Nix' => 'nix',
//        'Nsis' => 'nsis',
        'Objective C' => 'objectivec',
//        'Ocaml' => 'ocaml',
        'Pascal' => 'pascal',
        'Perl' => 'perl',
        'PgSQL' => 'pgsql',
        'Php' => 'php',
//        'Pig' => 'pig',
        'Plain Text' => 'plain_text',
        'Powershell' => 'powershell',
//        'Praat' => 'praat',
//        'Prolog' => 'prolog',
        'Properties' => 'properties',
//        'Protobuf' => 'protobuf',
        'Python' => 'python',
//        'R' => 'r',
//        'Razor' => 'razor',
//        'Rdoc' => 'rdoc',
//        'Rhtml' => 'rhtml',
//        'Rst' => 'rst',
        'Ruby' => 'ruby',
        'Rust' => 'rust',
        'SASS' => 'sass',
//        'Scad' => 'scad',
        'Scala' => 'scala',
        'Scheme' => 'scheme',
        'SCSS' => 'scss',
//        'Sh' => 'sh',
//        'Sjs' => 'sjs',
//        'Smarty' => 'smarty',
//        'Snippets' => 'snippets',
//        'Soy Template' => 'soy_template',
//        'Space' => 'space',
//        'Sparql' => 'sparql',
        'SQL' => 'sql',
        'MSSQL' => 'sqlserver',
//        'Stylus' => 'stylus',
        'SVG' => 'svg',
        'Swift' => 'swift',
//        'Swig' => 'swig',
//        'Tcl' => 'tcl',
        'Tex' => 'tex',
        'Text' => 'text',
//        'Textile' => 'textile',
//        'Toml' => 'toml',
//        'Tsx' => 'tsx',
//        'Turtle' => 'turtle',
        'Twig' => 'twig',
        'Typescript' => 'typescript',
//        'Vala' => 'vala',
        'VBScript' => 'vbscript',
//        'Velocity' => 'velocity',
//        'Verilog' => 'verilog',
//        'VHDL' => 'vhdl',
//        'Wollok' => 'wollok',
        'XML' => 'xml',
        'XQuery' => 'xquery',
        'YAML' => 'yaml'
    );
}